### ISSUE TITLE
Add support for "smart" styles

### ISSUE THREAD

**Issue by kyleam** [pyout/pyout#1]
Things like auto-width, colorizing based on the field value (both
labels and numerical values), etc.

---

@yarikoptic's edits:

Things like 
- [x] auto-width (@yarikoptic thinks it is done already)
- [ ] styling based on the field value
  - [ ] on specific values
  - [ ] on ranges 
  - @yarikoptic thinks it could be done via the same spec, e.g:
```python
value_based = {
 None : {'color': 'black'},  # well -- when None
 ('bad', 'horrible') : {'color': 'green'}, # if any of those (set isn't hashable :-/) - that style
 pyout.intervals(10.23, 11): [
    {'color': 'blue'}, #  v < 10.23
    {'color': 'yellow'}, # 10.23 <= v < 11
    {'color': 'red', 'bold': True}, # 11 <= v
 ],
 pyout.percentiles(95, 99): [  # doesn't need to be now, but would help to think about it
    {'color': 'blue'}, #  v within first 95% of values seen so far for that column
    {'color': 'yellow'}, # 95% <= %v < 99%
    {'color': 'red', 'bold': True}, # 99% <= %v
 ],
}
```

**Comment by yarikoptic** [comment]
this is a composite issue ;)  auto-width should be indeed done among the first ones.  The other features could wait

**Comment by kyleam** [comment]
> auto-width should be indeed done among the first ones

along with auto-width, some sort of truncation option would be nice

**Comment by kyleam** [comment]
Related comments:  
 * https://github.com/pyout/pyout/pull/14#discussion_r158507976
  * https://github.com/pyout/pyout/pull/14#discussion_r158508310

**Comment by kyleam** [comment]
> on specific values
> on ranges

These are already possible.  Can you say why you prefer your proposed
syntax to the present one?

**Comment by yarikoptic** [comment]
I must have missed it in the documentation and the issue was still open, so assumed that it is not yet implemented. Could you please point blind me to the example or test?

**Comment by kyleam** [comment]
Perhaps one of your objections would be that you want to be able to
define multiple aspects of a style ({'color': 'red', 'bold': True},
not just bold or color) based on the value/range mapping.  That's not
currently possible.

**Comment by kyleam** [comment]
You can see one example [here].  Also there are some examples in the
tests starting at [line 506].  And the "label" and "interval" part of
the [schema].

[here]: https://github.com/pyout/pyout/pull/24#issuecomment-355681505
[line 506]: https://github.com/pyout/pyout/blob/c684becf8da8ce0c1e813a5f3a42034ec01afa34/test_pyout.py#L506
[schema]: https://github.com/pyout/pyout/blob/c684becf8da8ce0c1e813a5f3a42034ec01afa34/pyout.py#L75

**Comment by yarikoptic** [comment]
Ah cool, sorry I have missed it. I guess it is as good ;-)
I am  not sure about interval syntax - ambiguous since allows for gaps and overlaps sure to duplicates of values to specify the ranges. And I guess it does allow mixing them:  a callback value result which will be a number (ranges) and meanwhile yellow "waiting"? Right?

**Comment by yarikoptic** [comment]
Add for the objection guess - it still would be possible, won't it? I just would need to define it both for bold and color separately, right?

**Comment by kyleam** [comment]
> I just would need to define it both for bold and color separately, right?

correct

**Comment by kyleam** [comment]
> I am not sure about interval syntax - ambiguous since allows for gaps and overlaps sure to duplicates of values to specify the ranges

Gaps just keep the default style.  For overlaps, the first interval
hit in the list would be applied.

**Comment by kyleam** [comment]
> And I guess it does allow mixing them: a callback value result which will be a number (ranges) and meanwhile yellow "waiting"? Right?

Right, when rows are rewritten, the styles are refreshed.

**Comment by kyleam** [comment]
Closing this.  Any specific issues with the current implementation/syntax can be discussed in dedicated issues.
