### ISSUE TITLE
TypeError if `columns` argument to `Tabular` is a tuple

### ISSUE THREAD

**Issue by jwodder** [pyout/pyout#110]
If a tuple is passed as the `columns` parameter to `Tabular`, a `TypeError` (`can only concatenate tuple (not "list") to tuple`) can result on [this line](https://github.com/pyout/pyout/blob/master/pyout/common.py#L145).  This was observed with pyout 0.6.0.  pyout should always(?) cast `columns` to a list in order to avoid this.

**Comment by kyleam** [comment]
Thanks for reporting.  Resolved by #111, which I'll plan to merge in later today.

**Comment by yarikoptic** [comment]
FWIW, we worked around on `dandi-cli` level as well, but not ready for release yet, and some users started to trip on this. Could there be a quick pyout release with #111?

**Comment by kyleam** [comment]
> Could there be a quick pyout release with #111?

Sure, will do today.
