### ISSUE TITLE
no output at all under Jupyter

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#120]
a follow up to #118 where I ran
```python
from dandi.download import download
download('DANDI:000027', '/tmp/', existing='overwrite')
```
it produced no output from pyout whatsoever.

NB if you try on hub.dandiarchive.org, you might need first to `pip install --upgrade dandi pyout`

I am not sure if it is easily possible to make `pyout` dynamically rerender itself in jupyter cell output without creating a totally new jupyter widget.  So may be if it detects being ran in jupyter, it could just switch to the same "provide final rendering" mode? (or ideally - render each line as it is finalized, #119, but that is an orthogonal issue).

**Comment by kyleam** [comment]
I can trigger the issue in a notebook with just this in a cell:

```python
from pyout import Tabular
with Tabular(columns=["name", "path"]) as out:
    out(["x", "y"])
```

I'll take a closer look sometime this week.
