### ISSUE TITLE
auto releasing seems stuck

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#135]
#133 add it, and was merged with `release`.
But releasing seems got stuck on "Create release" already for 17 minutes

**Comment by jwodder** [comment]
@yarikoptic The first run failed almost immediately due to hitting a GitHub secondary rate limit, so I reran it.  Now it's waiting 58 minutes for the rate limit to refresh.

**Comment by yarikoptic** [comment]
hm, why it hit the limit if this is so fresh -- too many PRs from the past to process? (this issue is just 135, so seems not that many were total in the past)

**Comment by jwodder** [comment]
@yarikoptic I think that's it — there's no GitHub release for the previous version, so it's starting from the beginning.  Even if that's not it, we do need to create a release for the previous tag.  I'm going to cancel the current run in case it downloaded any data, create a release, wait an hour, and then try again.

**Comment by jwodder** [comment]
@yarikoptic The workflow ran successfully the third time.

**Comment by yarikoptic** [comment]
great, thank you!  I see 0.7.2 on pypi and also release record on github.
