### ISSUE TITLE
Dependency on blessings

### ISSUE THREAD

**Issue by TheChymera** [pyout/pyout#136]
The [latest release of `blessings`](https://github.com/erikrose/blessings/releases/tag/1.7) appears to have been almost 5 years ago. It also still uses nose, and does not seem to have been active or interested in switching for about 3 years → https://github.com/erikrose/blessings/issues/164 .

I [sent a PR](https://github.com/erikrose/blessings/pull/165), but pytest doesn't quite work as a drop-in replacement, and even if I figure it out, upstream might not want to pull.

Would you be interested in (1) helping update blessings? or could it perhaps be (2) dropped and replaced by something else?

**Comment by jwodder** [comment]
For the record, I believe [blessed](https://github.com/jquast/blessed) is the maintained alternative to blessings.

**Comment by yarikoptic** [comment]
Oh, great find. Pity they had to fork instead of taking over. @TheChymera please propose PR which would prefer blessed over blessings but would allow for either to be used to smooth the migration
