### ISSUE TITLE
Move temporary style change to context manager?

### ISSUE THREAD

**Issue by kyleam** [pyout/pyout#16]
Instead of (or in addition to?)

```python
out({"name": "bar", "status": "BAD"},
    style={"status": {"color": "red", "bold": True}})
```

it would be nice to be able to say

```python
with out.style({"status": {"color": "red", "bold": True}}):
    out({"name": "bar", "status": "BAD"})
```

**Comment by yarikoptic** [comment]
Might be cute indeed, but not sure if I would see myself using it often

**Comment by kyleam** [comment]
fair enough

I suppose two practical advantages would be

  1) for multiple calls to out within the same context.  If I was
     using the first form with the style argument, I'd want to assign
     the style with a variable that I pass to each `out` call, which
     isn't bad but it's nice to be able to avoid.

  2) nesting contexts might be a natural way to build on styles.  Not
     sure there's a need to do that though, but could be useful.

Still probably falls in the realm of "cute" though.

**Comment by kyleam** [comment]
I have no plans to take this idea any further.
