### ISSUE TITLE
0.1.0?

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#27]
As I am starting to use it, there is no convenient way to install some working version of pyout.  Having a release uploaded to PyPI would be quite handy. What issues/features @kyleam would you like to implement before releasing the beast?

The https://github.com/pyout/pyout/milestone/1 lists only appveyor integration left, so either more issues to be associated or it would be cool to move that #13 into 0.2.0 milestone

**Comment by kyleam** [comment]
#13 (i.e., some sort of Windows support) was main blocker in my mind.
I'm fine moving that to 0.2.0.

**Comment by yarikoptic** [comment]
Done.  So, any issue to be assigned to 0.1.0 milestone from your point of view, or it could be released?

BTW, I am yarikoptic on pypi as well, for the bus effect, please add me as well to pypi maintainers for pyout on pypi

**Comment by kyleam** [comment]
> So, any issue to be assigned to 0.1.0 milestone from your point of view, or it could be released?

No, should be good to release.  Might as well merge #26 though.

**Comment by yarikoptic** [comment]
cool, I helped with that ;)

**Comment by kyleam** [comment]
done: https://pypi.python.org/pypi/pyout
