### ISSUE TITLE
"label" -> "enum" or alike?

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#44]
Although originally `enum` is for enumerating and in our case to assign arbitrary style values, I feel that it might be a better fit instead of a `label`. just an idea, feel free to close

**Comment by kyleam** [comment]
why?

**Comment by kyleam** [comment]
I'm not particularly attached to "label".  I also considered "value".
I don't like enum because to me it implies a collection with a defined
number, but that's not the intended behavior.  The values can be
anything, it's just that when we see this particular
value/label/whatever, we apply the given style element.  Other values
are just passed through.

**Comment by yarikoptic** [comment]
`label` is not really descriptive of the "function" here. `value` is indeed better.  let's sleep on it and consider in conjunction with other possible similar extensions like
`relative-interval` -- the one we talked about, but you offered an alternative approach which might be more flexible:  add `style-transform = callable` (just came up with this name) to transform the value first into the what would be considered for styling, and then possibly apply any of other (`interval`, `label`). The only gotcha that this callable would need to be provided all known values (may be from the "future" as well? ;))

**Comment by kyleam** [comment]
> label is not really descriptive of the "function" here

I don't view it a less descriptive than "interval".  For "interval",
you're matching on an interval.  For "label" you're matching on a
specific label/text/value (whatever you want to call it) like "OK",
"GOOD", "BAD" and applying a style.  Anyway, I'm fine changing it to
"value", but I don't see how it's more descriptive of the "function".

**Comment by yarikoptic** [comment]
ha -- you figured it out with it #47: `"lookup"` -- describes it best IMHO

**Comment by yarikoptic** [comment]
re regular expression, the use case didn't make wait for it too long to detect percent fields ;-) e.g. in my mighty "pyout! just do it" #45 I would have colored the percents...
```shell

$> cat /tmp/annex-json-output.json  | PYTHONPATH=/home/yoh/proj/repronim/pyout/ /home/yoh/proj/repronim/pyout/examples/color_json.py 
Set ids to be  ['key']
FILE                 NOTE        COMMAND KEY                  BYTE-PROGRESS TOTAL-SIZE PERCENT-PROGRESS
sub-01/anat/sub-0... from gin... get     MD5E-s5663237--46... 1146444       5663237    20.24%          
sub-01/anat/sub-0... from gin... get     MD5E-s5663237--46... 3145292       5663237    55.54%          
```
BUT I am wondering if there could be a more generic "switch" functionality (callable) which would allow to decide on further way to style output depending on what it gets (current and all other values ideally). Then for some (internally deciding on regex or whatever) it might decide to tune colors, for others something else.  I guess I could have been doing it outside of the Tabular but then I would need to be able possibly to adjust style on the fly and cause redraw -- may be that is already possible?  On the other hand I feel like I then would be redoing what Tabular is largely doing already.

**Comment by kyleam** [comment]
Presumably you intended to post this comment for #46.

**Comment by yarikoptic** [comment]
yeap, sorry -- will move there ;)
