### ISSUE TITLE
Should expand the list of columns whenever obtaining a new one it didn't see before

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#49]
ATM cares only about the columns discovered in the first entry:
```shell
$> echo -e '{"f": 1}\n{"f": 2, "f2":3}' | PYTHONPATH=/home/yoh/proj/repronim/pyout/ /home/yoh/proj/repronim/pyout/examples/color_json.py   
F
1
2
```

**Comment by kyleam** [comment]
Right (#2):

https://github.com/pyout/pyout/blob/5c6e7d9ea60e63704333e554567561df1123bd3f/pyout/tabular.py#L84-L87

I suppose this only becomes relevant now that we allow data to be
missing column names (#40).

**Comment by yarikoptic** [comment]
Ah, you haven't read between your own lines of #2 which never mentioned "first row" ;-)  and yeah -- practically relevant only when allowing missing columns which you do now

**Comment by kyleam** [comment]
> you haven't read between your own lines of #2 which never mentioned "first row"

Rows couldn't have missing keys then, so there were no lines to read between.

**Comment by yarikoptic** [comment]
It was written in between of between the rows -- nothing mentioned "missing keys" in #2 either ;)

**Comment by kyleam** [comment]
> It was written in between of between the rows -- nothing mentioned "missing keys" in #2 either ;)

I have no idea what the sentence means.

**Comment by yarikoptic** [comment]
I would like to bring back attention to this wishlist @kyleam .
It would be super useful in the context of `dandi ls` to be able to "add" columns dynamically. Files metadata fields with non-empty values could vary (and I do not want to even see the columns where none of the files has any value), and since we do not want to preload all files first to figure out which fields have some value in some file, it would be great if pyout could handle this situation for us.
Do you think it is possible to achieve without significant development investment?

**Comment by kyleam** [comment]
>  Do you think it is possible to achieve without significant development investment?

I don't know without looking into it.  The assumption that the keys are known is probably very baked in, but it might take that much to change (though I don't think it is a good idea).

**Comment by yarikoptic** [comment]
Another approach which would work for me would be to provide pyout all the keys all the time, but have an option for it to not visualize any column which has no value (ie just empty string or none) in any of the rows
