### ISSUE TITLE
Decide how to handle stderr

### ISSUE THREAD

**Issue by kyleam** [pyout/pyout#5]
Right now it messes of the `moveback` logic, resulting in the wrong
line being updated.

**Comment by yarikoptic** [comment]
I don't think we would be able to do anything about this... or there is hope?

But if pyout would eventually be used as a "backend" (do not remember the official term) for logging module output, it would probably need to use stdout if any terminal ANSI movement would be needed

**Comment by kyleam** [comment]
I don't have any plans or ideas for dealing with this at the moment.
