### ISSUE TITLE
__call__ should handle `rewrite`

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#50]
So I am setting `.ids` to be `['key']` and expected the row gets updated if a row with the same key was provided, seems to be not happening (requires explicit call to `.rewrite`?)

```shell
$> echo -e '{"key": 1, "v":0}\n{"key": 1, "v":1}' | PYTHONPATH=/home/yoh/proj/repronim/pyout/ /home/yoh/proj/repronim/pyout/examples/color_json.py
Set ids to be  ['key']
KEY V
1   0
1   1
```

**Comment by kyleam** [comment]
Duplicate of #20.
