### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by kyleam** [pyout/pyout#58]
![](https://avatars3.githubusercontent.com/u/34486283?s=200&v=4)

this guy's nice and all but ...

**Comment by yarikoptic** [comment]
what -- me to come up with the logo? oi... ok, I will bombard you with some ideas later, but they will not be pretty I am afraid ;)

**Comment by yarikoptic** [comment]
oh, the only issue which is assigned to me and I failed to handle it... ok, placing a more difficult idea aside, what about
![drop svg](https://user-images.githubusercontent.com/39889/49768650-077c6480-fcab-11e8-81b5-b23a0a24c430.png)
or it is too vulgar ? ;)  on pros -- concise, easy to remember/draw ;)

**Comment by kyleam** [comment]
Thanks, but it doesn't really speak to me.

Anyway, no reason to waste time on this.  I'll revisit it if I ever feel inspired.

**Comment by kyleam** [comment]
>  but not sure if PSF layers wouldn't upon us

perhaps :]

> has both "py" and "out" (if not through ;))

Indeed.  I like that it's direct, but for whatever reason I'm not a huge fan of using a snake cartoon.

Here is my snakeless and less interpretable attempt that I showed you in person:

![logo](https://user-images.githubusercontent.com/1297788/49880669-a663a680-fdfa-11e8-88ff-7272fb3b6fed.png)

I believe your reaction was mixed: certainly harder to decode but probably more usable as a logo.

**Comment by yarikoptic** [comment]
FWIW, I like it more now, especially since could be done in ascii `{>}` ;-)

**Comment by yarikoptic** [comment]
Not sure if black background communicates terminal, so much be worth just dropping it all for a cleaner view

**Comment by kyleam** [comment]
> Not sure if black background communicates terminal, so much be worth just dropping it all for a cleaner view

Yeah, that's a good point.  I'm not sure either.  For comparison:

![logo_nobackground svg](https://user-images.githubusercontent.com/1297788/49882523-ce550900-fdfe-11e8-971d-7b858798cde4.png)

**Comment by yarikoptic** [comment]
what about using the same dark grey as you had it for the background?  otherwise feels like too much contrast against the pale green

**Comment by kyleam** [comment]
> what about using the same dark grey as you had it for the background?

Hm, that's what I intended to do, but it looks like I didn't.  Although I didn't really fiddle much with the colors to begin with, so they could probably use more thought/tweaking.

![logo_nobackground svg](https://user-images.githubusercontent.com/1297788/49889606-f731ca00-fe0f-11e8-96c1-d0158e8d5503.png)

**Comment by yarikoptic** [comment]
I convinced myself that it looks better ;-)

**Comment by yarikoptic** [comment]
actually according to https://user-images.githubusercontent.com/1297788/49882523-ce550900-fdfe-11e8-971d-7b858798cde4.png  you did have it off-black a bit so it was visible, but now it is visible even better  https://user-images.githubusercontent.com/1297788/49889606-f731ca00-fe0f-11e8-96c1-d0158e8d5503.png

**Comment by yarikoptic** [comment]
thanks for svg, I didn't dare to ask ;)  IMHO it is good as is, only may be for the some uses adding a shadow wouldn't hurt but I do not feel any strong about it

![pyout-logo-shadow](https://user-images.githubusercontent.com/39889/49892079-17fd1e00-fe16-11e8-9931-c420e63e7637.png)

Also may be placing it on top of explicit white box/circle could help use it regardless of the background

**Comment by kyleam** [comment]
> only may be for the some uses adding a shadow wouldn't hurt but I do not feel any strong about it

all right, since you don't feel strongly, I'll stick with simple and boring :]

> Also may be placing it on top of explicit white box/circle could help use it regardless of the background

Yeah, I wasn't sure about this.  Seems the datalad organization logo doesn't.  I guess we can leave it as is and adjust or add variants as needed.

**Comment by kyleam** [comment]
Updated organization's logo.

**Comment by yarikoptic** [comment]
Woohoo! Congratulations.
Next one needs to be done for @kyleam but there is nowhere to file an issue ;-)

**Comment by kyleam** [comment]
> Next one needs to be done for @kyleam but there is nowhere to file an issue ;-)

:]
