### ISSUE TITLE
be able to specify the "style" of truncation

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#67]
ATM [Truncater](https://github.com/pyout/pyout/blob/master/pyout/field.py#L204) just truncates from the right, so I obtain smth like:
```shell
$> datalad ls -r ~/datalad/openfmri/ds000001 -L
PATH                 TYPE BRANCH DESCRIBE DATE CLEAN ANNEX_LOCAL ANNEX_WORKTREE
/home/yoh/datalad... a... master 2.0.4... 2... X                               
Summary:              ...                 e...  c... 0 Bytes     0 Bytes       
                                          l...                               
```
IMHO for some fields (like path), it would be more sensible to truncate from the left (thus having `...ri/ds00001` in my case above) and may be even in the middle in some weird cases (although nothing really like that comes to my mind ATM, but may be sizes so you could see leading digits and then the units at the end).  So I would have loved to be able to specify in my `path` style record, which is currently 
```python
            ('path', dict(
                bold=True,
                align="left",
                underline=True,
                aggregate=lambda _: "Summary:"
            )),
```
to truncate on the left.

**Comment by kyleam** [comment]
I agree that it'd be good to support left and center truncation styles.

> ATM [Truncater](https://github.com/pyout/pyout/blob/master/pyout/field.py#L204) just truncates 

There is a relevant TODO comment within the class you link to:

https://github.com/pyout/pyout/blob/e1fc3e8884d93e51c7ac0dab86f20c88c1777f11/pyout/field.py#L225-L226
