### ISSUE TITLE
Make width as large as needed in "final" mode

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#70]
If stdout it not a tty ATM pytout seems to limit to some predetermined width:
```shell
$> datalad ls -r ~/datalad -L | cat 
[3]  - 3355 done       gitk --all
PATH              TYPE  BRANCH DESCRIBE DATE          CLEAN ANNEX(PRESENT) ANNEX(WORKTREE)
/home/yoh/datalad annex master          2018-09-17... -     31.3 MB        23.8 MB        
/home/yoh/data... annex master 0.0.2... 2018-06-08... X     0 Bytes        0 Bytes        
/home/yoh/data... annex master          2018-06-08... X     0 Bytes        0 Bytes        
...
```
but since delivering the "final" rendering -- why not to make it as wide as needed?  
Also then It would correspond to the final version of the "update" mode output

**Comment by kyleam** [comment]
> but since delivering the "final" rendering -- why not to make it as wide as needed?

That wouldn't work for any "final" rendering because that might still be tty, but I agree it'd make sense to use as wide as needed when stdout is not a tty.

> Also then It would correspond to the final version of the "update" mode output

I don't understand this statement.

**Comment by yarikoptic** [comment]
> > but since delivering the "final" rendering -- why not to make it as wide as needed?
> 
> That wouldn't work for "final" rendering in general because stdout might still be a tty, but I agree it'd make sense to use as wide as needed when stdout is not a tty.
> 
> > Also then It would correspond to the final version of the "update" mode output
> 
> I don't understand this statement.

that it would look similar to output without `| cat` on a wide-enough terminal.  ATM regardless of the width of the terminal, it always squeezes it so output with `| cat` looks different

**Comment by kyleam** [comment]
> > > Also then It would correspond to the final version of the "update" mode output
> > 
> > 
> > I don't understand this statement.
> 
> that it would look similar to output without `| cat` on a wide-enough terminal. ATM regardless of the width of the terminal, it always squeezes it so output with `| cat` looks different

I see.  What confused me is the "then final would correspond to update" part.  The request is that in the non-tty case, final should use as wide as needed, which doesn't correspond to the update/tty case of using the terminal width. 

The `| cat` case doesn't match the terminal width because, in the non-tty case, `term.width` is None and we currently default to style's `width_` (90).
