### ISSUE TITLE
Support "wait for callbacks" for rows that would go offscreen

### ISSUE THREAD

**Issue by kyleam** [pyout/pyout#74]
https://github.com/pyout/pyout/pull/72#issuecomment-447901764

**Comment by yarikoptic** [comment]
Would be nice to have this implemented! 
ATM, for `dandi ls`, we quickly populate all the rows (in 100s), many of which take awhile to actually open a file and provide desired data.  This results in constant redrawing the big table, so to the user actually no updates are visible (pyout quickly gets back to the bottom of the table in its redrawing pass), just some blinking.  Eventually it reaches bottom rows, and those start to get updated on the screen.

When scrolling terminal buffer after it becomes possible to see all those full table dumps where only some top rows got updated.
