### ISSUE TITLE
May be Outputter -> Tabular?

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#8]
I adjusted description of the project a bit ...
ATM indeed the main target is tabular output, but may be we will get a number of different ones etc.  So I thought, why not to state explicitly the nature of this one in the class name? ;)  `from pyout import Tabular` makes sense somewhat

**Comment by kyleam** [comment]
> I adjusted description of the project a bit ...

Thanks.  I'm viewing all the descriptions (in README, GitHub, module)
as placeholders for now, so please adjust as you see fit.


> So I thought, why not to state explicitly the nature of this one in the class name? ;) from pyout import Tabular makes sense somewhat

Tabular sounds fine to me.  I'm pretty set on changing that class name
though, so nearly any argument would convince me :)

I've though about some how getting "Style*" into the name but haven't
come up with anything I like.

**Comment by yarikoptic** [comment]
Ha, actually I also thought about "Style"s but may be also a bit ahead of time -- that we might want to separate presentation Styles (i.e. Model) from how/where it would be presented (View?).  Kinda, may be, at some point, in the future, we could potentially have multiple styles associated with different types of output presented in different locations (e.g. that Summary progressbar presented at the very bottom of all other elements of different Styles (such as Tabular) above it).  But that could come in the future, although I already see myself excitingly monitoring "Summary" total line following output of "datalad ls"  with accumulating numbers as more and more lines provide their output for the sizes ;)  but that is later... for now the **Tabular** should suffice
