### ISSUE TITLE
RF: Outputter should not get data in constructor

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#9]
IMHO constructor should just define parameters of the output (style(s), stream, etc), not the actual data, which is typically not known all at once. `.write()` should get a single or multiple (if list or a tuple) record(s). If mode requires, could even store them in its `_rows` to go back etc.

**Comment by kyleam** [comment]
> If mode requires, could even store them in its _rows to go back etc.

Right, that's my plan once `data` stops forcing a list (I think I just
have a TODO/FIXME comment for that, not an open issue).

Anyway, I agree that it makes sense to remove the `data` argument from
`__init__`.

Thanks.
